export enum Language {
  English = "english",
  ChineseSimplified = "chinese_simplified",
  ChineseTraditional = "chinese_traditional",
  Japanese = "japanese",
  Korean = "korean",
  Spanish = "spanish",
  French = "french",
  German = "german",
  Italian = "italian",
  Polish = "polish",
  Czech = "czech",
  Portuguese = "portuguese",
  Turkish = "turkish",
  Ukrainian = "ukrainian",
  Russian = "russian",
}

export default [
  "English",
  "Chinese - Simplified",
  "Chinese - Traditional",
  "Japanese",
  "Korean",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Polish",
  "Czech",
  "Portuguese",
  "Turkish",
  "Ukrainian",
  "Russian",
];
