// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateModZip(arg1, arg2) {
  return window['go']['main']['App']['CreateModZip'](arg1, arg2);
}

export function OpenGitHub() {
  return window['go']['main']['App']['OpenGitHub']();
}

export function OpenNexusMod() {
  return window['go']['main']['App']['OpenNexusMod']();
}

export function SelectGameFolder() {
  return window['go']['main']['App']['SelectGameFolder']();
}
