// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateModZip(arg1:string,arg2:string):Promise<void>;

export function OpenGitHub():Promise<void>;

export function OpenNexusMod():Promise<void>;

export function SelectGameFolder():Promise<string>;
