// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateModZip() {
  return window['go']['main']['App']['CreateModZip']();
}

export function SelectGameFolder() {
  return window['go']['main']['App']['SelectGameFolder']();
}
