// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateModZip():Promise<void>;

export function SelectGameFolder():Promise<string>;
